### ISSUE TITLE
Categories and inclusion tags

### ISSUE THREAD

**Issue by AndySky21** [middlebury/CategorySuggest#16]
The current version of the extension ignores &lt;noinclude&gt;d categories, while it strips &lt;includeonly&gt; tags. Which is awkward, because if &lt;includeonly&gt; tags are inserted in the page then the tag is useless, while authors have no help in &lt;noinclude&gt;.
An "advanced categories" form section with 2 additional input fields, for &lt;includeonly&gt; and &lt;noinclude&gt;, would ignore really complex cases such as chain transclusions (the case of &lt;include&lt;noinclude&gt;&lt;/noinclude&gt;only&gt;, and it'd also become a bit confusing.
This is my proposal (which I can work on): once chosen (either from the list or typing ";"), a category is listed in a block of draggable objects below the input field. Hence they can be loaded into the textarea as usual, by submitting, or can be dragdropped in specific points of the text, where they release the wikitext for the tag.

**Comment by adamfranco** [comment]
Hi @AndySky21 , as of b53c1d46d523e4d71b77b596071a1d2e687db530 CategorySuggest is now skipping categories in <includeOnly> tags. As far as I know this should solve the issue of tags needing to be in certain places in the text.

A draggable category list could be a neat feature, but sounds like it might be a lot of work for a relatively edge-case scenario. If you think that the additions in b53c1d46d523e4d71b77b596071a1d2e687db530 are sufficient, then go ahead and close this issue. Otherwise lets figure out what needs to be done to support other cases.

**Comment by AndySky21** [comment]
Hey @adamfranco ! I don't know what to answer, because it's not my job so I feel a little bit misplaced in getting my hands on it.
Thus said, I think that suggesting categories is really useful and it would be a great improvement if they could be suggested also for some edge cases. I admit that categories inside <noinclude> can be easily handled by admins, but <include>d categories can be edited inside template as new categories are created.
I will try to make something up for today and tomorrow, so you can see the result.

**Comment by AndySky21** [comment]
After recent work, I think that there's no real issue with that. Categories in special tags are not a layman's matter and anyway the "link" editor command can be enough. This extension serves the majority of the cases as it is. So i will close this report.
