### ISSUE TITLE
Empty lines of Preformatted text being lost when being save

### ISSUE THREAD

**Issue by quark5980** [middlebury/CategorySuggest#22]
When creating preformatted text by adding a space to the beginning of the line the first, if you have blank line (just the leading space) and save the article the formatting is fine

When editing and resaving the article (even with out changing anything), the spaces that were placed on the blank lines of the preformatted text are appearantly stripped out and the formatting is then messed up.  I would guess the text is getting stripped when it is loaded in the editor

**Comment by bogota** [comment]
I made a testcase wikitext which can be pasted to editbox to reproduce this issue.
https://gist.github.com/bogota/9b57ff27e43c0aa52ef9
(Don't forget to copy and paste it in "Raw" mode of Gist or download it from "Download Gist" button.)

Removing "rtrim" at https://github.com/middlebury/CategorySuggest/blob/master/CategorySuggest.body.php#L193 seems to fix the issue and produce no side effects for now, although I don't surely know for what the rtrim is there.

**Comment by adamfranco** [comment]
Thanks for the report and suggested fix. I looked at the history and the `rtrim()` call was in the initial commit, so I don't know why it was added. It seems like a *not* stripping trailing whitespace would be a safe thing to do. The only side effect I can think of would be a possible duplication of line ending characters, but that really shouldn't happen either.

If anyone has a chance, patches and further testing are welcome!

**Comment by quark5980** [comment]
I found the same thing with removing the rtrim in our of our test environment, and so far I haven't seen any isssues

**Comment by bogota** [comment]
> The only side effect I can think of would be a possible duplication of line ending characters, but that really shouldn't happen either.

Perhaps it is the case that the rtrim is doing some sort of cleanup. It would be good or at least harmless as far as it is done as post processing of removing Category tags. The problem is that non-Category lines are also rtrimmed almost unconditionally, which is the source of issue #22. 

So I think that modifying the code to do rtrimming only for Category lines like below could be another solution. It may be preferable than abolishing rtrim totally in view of compatibility.

https://github.com/middlebury/CategorySuggest/compare/master...bogota:%2322fix_proposal_01

It won't touch preformatted paragraphs anymore(except for those containing Category tags, which can be considered as rare cases), while rtrimming redundant spaces of Category lines.

**Comment by adamfranco** [comment]
This looks like a good improvement. If there is nothing further you'd like to change, submit a pull request and I'll merge it in.

**Comment by adamfranco** [comment]
Thanks again for working on this @quark5980 and @bogota !
